version: '3.7'

services:
  webapp:
    build: webapp
    user: root
    volumes:
      - /data/:/data/
    expose:
      - "3000"
      
  proxy:
    build: proxy
    ports:
      - "80:80"
    depends_on:
      - webapp

